import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is regenerated by `next dev`/`next build` — not ours to fix.
    ignores: ["node_modules/**", ".next/**", "public/**", "next-env.d.ts"],
  },
  {
    rules: {
      // The UI copy is entirely in French, which is apostrophe-heavy ("l'app",
      // "n'est", "aujourd'hui", ...). This rule exists for HTML-entity purism,
      // not correctness — a literal ' renders fine. Enforcing &apos; everywhere
      // would mean escaping dozens of routine strings for no functional gain.
      "react/no-unescaped-entities": "off",
    },
  },
];

export default eslintConfig;
